version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: uname -a
      - run:
          command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          environment:
            HOMEBREW_INSTALL_FROM_API: 1
            NONINTERACTIVE: 1
      - run: sbt Test/nativeLink
      - run: sbt test

workflows:
  ci:
    jobs:
      - test
