version: 2.1

jobs:
  test-arm:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: uname -a
      - run:
          name: Install clang
          command: sudo apt-get install clang
      - run:
          name: Install liburing
          command: |
            git clone https://github.com/axboe/liburing.git
            cd liburing
            ./configure
            make
            sudo make install
      - run: sbt test

workflows:
  ci:
    jobs:
      - test-arm
