version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: uname -a
      - run: brew install liburing
      - run: sbt Test/nativeLink
      - run: sbt test

workflows:
  ci:
    jobs:
      - test
